/**
 * Absorbing a stray branch into `main` without ever deleting work.
 *
 * The logic lives here, importable, rather than in `scripts/absorb-branches.mjs` (a thin CLI) or —
 * as it did until 2026-08-14 — inside a workflow's `run:` block, where **nothing could execute
 * it**. That is not incidental to the defect this file fixes: a race that silently destroyed the
 * athlete's logged data survived for as long as it lived somewhere untestable.
 * `scripts/test-git-sync.mjs` calls both halves — the whole job against real repositories, and
 * `deleteUnderLease` on its own, in the one-microsecond window that separates a safe delete from a
 * destructive one.
 *
 * ── F-04, THE DELETE RACE ────────────────────────────────────────────────────────────────────
 *
 * The old job read every remote ref once, at the top, then ran `git push origin --delete <branch>`
 * at the bottom. A commit pushed in between was merged into nothing and then deleted, with no
 * banner (the branch is gone, so the dashboard's stray-branch check comes back empty), no failed
 * run (the next absorb finds nothing and exits green), and no surface anywhere reporting it. The
 * meal simply was not in the chart. A production near-miss is on record at 36 seconds inside the
 * window (run 31741980162); sessions here push as often as 17 s apart.
 *
 * Two changes close it:
 *
 *   1. **A captured SHA is merged, not a ref name.** "What did I merge" is one specific commit
 *      that cannot drift under the job's feet.
 *   2. **The delete is leased on that SHA:**
 *
 *          git push --force-with-lease=<branch>:<sha> origin :<branch>
 *
 * The audit believed no `--force-with-lease` equivalent existed for deletes and proposed
 * re-fetching immediately before the delete to *narrow* the window. It exists, and the distinction
 * matters more than it sounds:
 *
 * > An ordinary `git push origin --delete` is not unguarded — git sends the ref value it saw in
 * > the remote's advertisement as the expected old value, so a push landing *after* the
 * > advertisement is rejected by the server. What it cannot do is notice a push that landed
 * > *before* the delete command started, because by then the advertisement already carries the new
 * > value. That is precisely the window a re-fetch narrows and cannot close: between the check and
 * > the advertisement. `--force-with-lease=<branch>:<sha>` replaces the advertised value with the
 * > SHA **this job decided from**, so the comparison is against what was actually merged.
 *
 * Verified on git 2.50.1 against two bare repositories, with the racing push fired from a
 * `receivepack` wrapper so it lands inside that exact window — the pre-check passing, the ref
 * moving, and then:
 *
 *     plain delete:  - [deleted]  feat                          exit 0   ← the commit is destroyed
 *     leased delete: ! [rejected] (delete) -> feat (stale info)  exit 1   ← the branch survives
 *
 * `scripts/test-git-sync.mjs` runs exactly that comparison, so the claim is checked rather than
 * believed. `remoteSha()` is kept as a cheap pre-check because it produces a clearer message than
 * git's, not because it is load-bearing.
 *
 * **The `AHEAD=0` early exit was the same bug** and gets the same protection. It was the worse
 * instance: it deleted on the stale read without merging anything at all.
 *
 * ── F-36, ONE BAD BRANCH BLOCKING EVERY OTHER BRANCH ─────────────────────────────────────────
 *
 * The old job merged every branch into one tree, validated once, and pushed all-or-nothing under
 * `set -euo pipefail`, so a validation failure from branch Y held back healthy branch X every hour,
 * indefinitely. Here each branch gets its own merge → validate → push → delete, from a tree freshly
 * reset to `origin/main`, so one branch's fate cannot touch another's.
 *
 * ── A BRANCH THAT MOVED IS NOT AN ERROR ──────────────────────────────────────────────────────
 *
 * When the lease refuses, the branch is left standing with its commits intact and reported as
 * `moved`. That is the mechanism working, not failing: the push that won the race is itself a push
 * to a non-`main` branch, so it re-triggers the workflow and the branch is absorbed seconds later.
 * It is a `::warning::` and does not fail the run — an hourly red X for a self-healing 17-second
 * race is how a maintainer learns to ignore absorb failures, which is the same harm F-45 describes
 * on the athlete's side. Conflicts, validation failures and exhausted pushes DO fail the run:
 * those need a human. If absorption ever genuinely stops, the alarm is the dashboard's
 * stray-branch banner, and after F-45 it is a trustworthy one.
 */
import { git, gitTry, revParse, countAhead } from './git.mjs'
import { strayBranchNames } from './branches.mjs'
import { pushWithRetry, ValidationError } from './push-retry.mjs'

/**
 * Regenerated by the check suite after a merge changes its inputs; committed with the merge.
 *
 * `targets.csv` is here because `check-all --regen-energy` fills a target gap rather than failing
 * on one (see `scripts/check-all.mjs`). Without it the fill would happen on every run and land in
 * no commit, so the gap would reopen immediately and this job would do the work forever.
 */
export const DERIVED_FILES = ['data/energy.csv', 'data/targets.csv']

/** A merge this job must not resolve: resolving means combining rows, which is a judgement call. */
export class ConflictError extends Error {
  constructor(message) { super(message); this.name = 'ConflictError' }
}

const ctxDefaults = (ctx = {}) => ({
  cwd: ctx.cwd ?? process.cwd(),
  remote: ctx.remote ?? 'origin',
  branch: ctx.branch ?? 'main',
  log: ctx.log ?? console.log,
})

/** Every branch on the remote that is not `main` and not under `keep/`. */
export function listStrayBranches(ctx) {
  const { cwd, remote } = ctxDefaults(ctx)
  const names = git(['branch', '-r', '--format=%(refname:short)'], { cwd })
    .split('\n')
    .map((s) => s.trim())
    .filter((s) => s.startsWith(`${remote}/`))
    .map((s) => s.slice(remote.length + 1))
    .filter((s) => s !== 'HEAD' && !s.startsWith('HEAD '))
  return strayBranchNames(names)
}

/** Start every branch from the same known state, so no branch can inherit another's mess. */
export function syncToMain(ctx) {
  const { cwd, remote, branch } = ctxDefaults(ctx)
  git(['fetch', remote, branch], { cwd })
  git(['reset', '--hard', `${remote}/${branch}`], { cwd })
}

/** What the remote says this branch points at right now; `null` if gone, `undefined` if unknown. */
export function remoteSha(name, ctx) {
  const { cwd, remote } = ctxDefaults(ctx)
  const ls = gitTry(['ls-remote', '--heads', remote, `refs/heads/${name}`], { cwd })
  if (ls.status !== 0) return undefined // could not ask; let the lease decide
  const line = ls.stdout.trim().split('\n')[0]
  return line ? line.split(/\s+/)[0] : null
}

/**
 * Delete `name` if and only if it still points at `sha`. Returns 'deleted' | 'moved' | 'gone'.
 *
 * The lease is what makes this safe; the `remoteSha` pre-check only buys a clearer message. See
 * the file header for the measured difference between the two.
 */
export function deleteUnderLease(name, sha, ctx) {
  const { cwd, remote } = ctxDefaults(ctx)
  const now = remoteSha(name, ctx)
  if (now === null) return 'gone'
  if (now !== undefined && now !== sha) return 'moved'

  const r = gitTry(['push', `--force-with-lease=${name}:${sha}`, remote, `:${name}`], { cwd })
  if (r.status === 0) return 'deleted'

  const err = `${r.stdout}\n${r.stderr}`
  // "stale info" is the lease refusing. "cannot lock ref"/"failed to update ref" is the server
  // refusing because the ref moved after it advertised. Both mean the same thing to us.
  if (/stale info|cannot lock ref|failed to update ref/.test(err)) return 'moved'
  if (/remote ref does not exist/.test(err)) return 'gone'
  throw new Error(`could not delete ${name}: ${err.trim()}`)
}

/**
 * Merge one branch, check it, push it, and delete it — independently of every other branch.
 *
 * Returns `{ branch, sha, outcome, merged }`. Throws ConflictError, ValidationError, or a plain
 * Error; the caller classifies and keeps going.
 */
export function absorbBranch(name, sha, ctx) {
  const c = ctxDefaults(ctx)
  syncToMain(c)

  const ahead = countAhead('HEAD', sha, { cwd: c.cwd })
  if (ahead === 0) {
    // Everything here is already on main. The old job deleted at this point from a snapshot read
    // minutes earlier, destroying anything pushed since without ever looking at it.
    return { branch: name, sha, outcome: deleteUnderLease(name, sha, c), merged: 0 }
  }

  c.log(`  ${ahead} commit(s) not on ${c.branch}:`)
  c.log(git(['log', `HEAD..${sha}`, '--oneline'], { cwd: c.cwd })
    .split('\n').map((l) => `    ${l}`).join('\n'))

  const applyMerge = () => {
    const m = gitTry(['merge', sha, '--no-edit'], { cwd: c.cwd })
    if (m.status !== 0) {
      gitTry(['merge', '--abort'], { cwd: c.cwd })
      throw new ConflictError(`${name} conflicts with ${c.branch}\n${(m.stdout || '').trim()}`)
    }
    return { changed: true }
  }

  const pushed = pushWithRetry({
    apply: applyMerge,
    message: `Recompute energy.csv after absorbing ${name}`,
    files: DERIVED_FILES,
    cwd: c.cwd,
    remote: c.remote,
    branch: c.branch,
    log: c.log,
  })

  return { branch: name, sha, outcome: deleteUnderLease(name, sha, c), merged: ahead, pushed: pushed.pushed }
}

/**
 * The whole job: every stray branch, each on its own, from one snapshot of SHAs taken up front.
 *
 * Returns one result per branch. Never throws for a single branch's failure — a branch that cannot
 * be absorbed is a result with an outcome, not an exception that takes the rest of them down.
 */
export function absorbAll(ctx) {
  const c = ctxDefaults(ctx)
  git(['fetch', c.remote, '--prune'], { cwd: c.cwd })

  const branches = listStrayBranches(c)
  if (!branches.length) return []

  // Captured ONCE, before any work: from here on every decision names a commit, not a moving ref.
  const captured = new Map(branches.map((b) => [b, revParse(`${c.remote}/${b}`, { cwd: c.cwd })]))
  c.log(`Stray branches found: ${branches.join(', ')}`)

  const results = []
  for (const name of branches) {
    const sha = captured.get(name)
    c.log(`::group::Absorbing ${name} @ ${sha}`)
    try {
      if (!sha) throw new Error(`${name} does not resolve to a commit`)
      results.push(absorbBranch(name, sha, c))
    } catch (e) {
      const outcome = e instanceof ConflictError ? 'conflict'
        : e instanceof ValidationError ? 'validation'
        : 'error'
      results.push({ branch: name, sha, outcome, detail: e.message })
    }
    c.log('::endgroup::')
  }

  // Leave the tree where the workflow found it, whatever happened above.
  try { syncToMain(c) } catch { /* the report is what matters */ }

  return results
}
